baetyl-409 remote debug
baetyl/baetyl pull request #553
Opened 2020-09-08 12:40 UTC by zxxf18

2020-09-10 02:32 UTC, ludanfeng requested changes

2020-09-10 02:32 UTC, ludanfeng commented on engine/remote_debug.go
> +				e.msg <- generateCommandReply(DebugStateOK, []byte("connect success"))
这个其实是一个消息中心，建议不要这样写，容易卡住和超时
sync和engine之间是不是需要一个消息中心解耦？

2020-09-10 02:32 UTC, ludanfeng commented on sync/sync.go
> +	CommandReceive() <-chan map[string]string
其他接口的命名都是动词在前

2020-09-14 16:11 UTC, ludanfeng commented on chain/msg_handler.go
> +package chain
咋又造了一个chain出来？

2020-09-14 16:11 UTC, ludanfeng commented on chain/chain.go
> +				"res": "500",
code?

2020-09-15 02:49 UTC, ludanfeng requested changes

2020-09-15 02:49 UTC, ludanfeng commented on ami/ami.go
> +	Container string
建议改成Instance，因为我们的应用模型没有这个概念

2020-09-15 02:49 UTC, ludanfeng commented on ami/kube/kube_exec.go
> +func (k *kubeImpl) RemoteDebug(option ami.DebugOptions, stdin io.Reader, stdout, stderr io.Writer) error {
stdin io.Reader, stdout, stderr io.Writer 包装成一个双向流stream，能直接用你定义的pipe吗？

2020-09-15 02:49 UTC, ludanfeng commented on chain/chain.go
> +	io.Closer
这些不都是mq的功能吗？如果设计上chain包了mq，那么超时的逻辑应该放在chain上，而不是mq上了。个人觉得一个概念就够了。

2020-09-15 02:49 UTC, ludanfeng commented on chain/chain.go
> +	}
这部分逻辑应该是kube实现里的内部逻辑吧？

2020-09-15 12:47 UTC, zxxf18 commented on ami/ami.go
> +	Container string
这个不是intance，应该是instance中的一个容器，我们现在不支持单pod多容器，所以这个字段其实一直都是空，这个字段名是后面kube_exec中官方数据结构的名字拿过来的

2020-09-15 12:47 UTC, zxxf18 commented on plugin/memory/config.go
> +	} `yaml:"defaultmq" json:"defaultmq"`
这里就是这个，作为默认的消息队列

2020-09-15 12:48 UTC, zxxf18 commented on chain/chain.go
> +	}
kube内已经写过了，这里写重复了，已删

2020-09-15 13:39 UTC, ludanfeng approved these changes
TODO: code refactor

2020-09-15 14:03 UTC, merged