add native ports mapping related
baetyl/baetyl pull request #558
Opened 2020-09-14 12:17 UTC by chensheng0

2020-09-14 13:43 UTC, ludanfeng requested changes

2020-09-14 13:43 UTC, ludanfeng commented on ami/native/native.go
> +	RuntimeDynamicPort = "BAETYL_SERVICE_DYNAMIC_PORT"
这个怎么不放baetyl-go里？

2020-09-14 13:43 UTC, ludanfeng commented on ami/native/native.go
> +	sync.RWMutex
这个已经沟通，不应该暴露出来

2020-09-14 13:43 UTC, ludanfeng commented on ami/native/native.go
> +			if app.Type == FunctionApp {
不用区分是否是function app

2020-09-14 13:43 UTC, ludanfeng commented on ami/native/native.go
> +				port, err := utils.GetAvailablePort("127.0.0.0")
需要限制动态端口的范围

2020-09-14 13:43 UTC, ludanfeng commented on ami/native/native.go
> +			impl.Unlock()
这个用法是不对的，并发apply app的时候回相互覆盖文件的数据。应该在一个锁里完成文件的读和修改，建议开发一个动态端口管理类吧，内部把事情做完，不要在这里展开端口的注入。明天再沟通吧

2020-09-16 03:51 UTC, chensheng0 commented on ami/native/native.go
> +			if app.Type == FunctionApp {
目前只托管函数服务，容器服务的动态端口不支持配置

2020-09-22 03:25 UTC, ludanfeng requested changes

2020-09-22 05:54 UTC, ludanfeng requested changes

2020-09-22 05:54 UTC, ludanfeng commented on ami/native/native.go
> +func setEnv(env *[]v1.Environment, key, value string) {
appendEnv(env []v1.Environment, key, value string) []v1.Environment {}

2020-09-22 06:08 UTC, ludanfeng approved these changes

2020-09-22 06:08 UTC, merged